package proyecto;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Auto extends javax.swing.JInternalFrame {

    ResultSet rs,rs2;
    Statement st,st2;
    String estado = "";

    private void conexion() {
        Connection cn;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tallerM", "root", "123a");
            //agrego los estos set para que pueda agregar selecionar los siguientes datos, y para pueda leer más consultas en la base de datos
            st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            st2 = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);

        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de Driver", "BD", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de SQL" + e.toString(), "BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Auto() {
        initComponents();
        conexion();
        MostrarTabla();
        idCliente();
        try {
            String sql = "select * from auto";
            rs = st.executeQuery(sql);
            rs2= st2.executeQuery(sql);

            if (rs.next()) {

                txtPlaca.setText(rs.getString("Placa"));
                txtModelo.setText(rs.getString("Modelo"));
                txtMarca.setText(rs.getString("Marca"));
                boxSizes.setSelectedIndex(Puesto_Index);
                txtFecha.setText(rs.getString("fecha_recibido"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla -Inicio-" + e.toString());
        }

    }

    private void MostrarTabla() {
        try {
            String sql = "Select * from auto";
            rs = st.executeQuery(sql);

            Object fila[] = new Object[7];
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("idAuto");
            modelo.addColumn("Placa");
            modelo.addColumn("idCliente");
            modelo.addColumn("Modelo");
            modelo.addColumn("Marca");
            modelo.addColumn("Tamaño");
            modelo.addColumn("fecha_recibido");

            if (!rs.isBeforeFirst()) {
                rs.beforeFirst();
            }
            while (rs.next()) {
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            tablaAutos.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla" + e.toString());
        }
    }
    
    String Puesto_t = "";
    int Puesto_Index = 0;

    private void ob_Puesto() {
        int Puesto = this.boxSizes.getSelectedIndex();
        switch (Puesto) {
            case 0:
                Puesto_t = "Grande";
                Puesto_Index = 0;
                break;
            case 1:
                Puesto_t = "Mediano";
                Puesto_Index = 1;

            case 2:
                Puesto_t = "Pequeño";
                break;
            case 3:
                Puesto_t = "Gerente";
                Puesto_Index = 2;
                break;
        }
    }
    
           private void idCliente(){
       try{ 
       Statement st12 = null;
       String sql2="Select * from cliente";
       rs=st.executeQuery(sql2);
       if(!rs.isBeforeFirst()){
           rs.beforeFirst();
       }
       while(rs.next()){
           
           boxNombre.addItem(rs.getString("Nombre"));
       }
       }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de SQL" + e.toString(), "BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        boxSizes = new javax.swing.JComboBox<>();
        boxNombre = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Auto");
        setPreferredSize(new java.awt.Dimension(1376, 786));

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel1.setText("Placa");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtPlaca.setText("Ingrese la placa");
        txtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaFocusLost(evt);
            }
        });
        txtPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPlacaMousePressed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAutos);

        jLabel3.setText("Nombre del cliente");

        txtModelo.setText("Ingrese el modelo del carro");
        txtModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModeloFocusLost(evt);
            }
        });
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtModeloMousePressed(evt);
            }
        });
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModeloKeyTyped(evt);
            }
        });

        jLabel6.setText("Tamaño");

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        jLabel4.setText("Modelo");

        jLabel5.setText("Marca");

        txtFecha.setText("Ingrese su telefono");
        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFocusLost(evt);
            }
        });
        txtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFechaMousePressed(evt);
            }
        });
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha");

        txtMarca.setText("Ingrese la marca del carro");
        txtMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMarcaFocusLost(evt);
            }
        });
        txtMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMarcaMousePressed(evt);
            }
        });
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        boxSizes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));
        boxSizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSizesActionPerformed(evt);
            }
        });

        boxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(369, 369, 369))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(247, 247, 247))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(447, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnNuevo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuardar)
                            .addGap(17, 17, 17)
                            .addComponent(btnEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnConsultar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalir)
                            .addGap(114, 114, 114))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(54, 54, 54)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUltimo)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior)
                    .addComponent(btnPrimero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo)
                        .addComponent(btnModificar)
                        .addComponent(btnCancelar)
                        .addComponent(btnGuardar)
                        .addComponent(btnEliminar)
                        .addComponent(btnConsultar)
                        .addComponent(btnSalir))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(142, 142, 142)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            //utilizo el metodo para ponerlo en siguiente
            rs.next();

            txtPlaca.setText(rs.getString("Placa"));
            txtModelo.setText(rs.getString("Modelo"));
            txtMarca.setText(rs.getString("Marca"));
            boxSizes.setSelectedItem(rs.getString("Tamaño"));
            txtFecha.setText(rs.getString("fecha_recibido"));
            
              String querty = "select * from cliente where idcliente ='" + rs.getString("Idcliente") +"'";
              rs2=st2.executeQuery(querty);
              if(rs2.next()){
              boxNombre.setSelectedItem(rs2.getString("Nombre"));
              }
            
            

            if (rs.isLast()) //si esta en el ultimo registro  si esta en el ultimo, si esta
            //en el ultimo entonces lo que hago es mandalo al antepeultimo
            {
                rs.beforeFirst();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try {
            //metodo de ultimo registro para que lo ponga en lo
            rs.last();
            //poner todos los registro que tiene la tabla en los campos de entrada

            txtPlaca.setText(rs.getString("Placa"));
            txtModelo.setText(rs.getString("Modelo"));
            txtMarca.setText(rs.getString("Marca"));
            boxSizes.setSelectedItem(rs.getString("Tamaño"));
            txtFecha.setText(rs.getString("fecha_recibido"));
            
              String querty = "select * from cliente where idcliente ='" + rs.getString("Idcliente") +"'";
              rs2=st2.executeQuery(querty);
              if(rs2.next()){
              boxNombre.setSelectedItem(rs2.getString("Nombre"));
              }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "n";

        txtPlaca.setText("");
        txtModelo.setText("");
        txtMarca.setText("");
        txtFecha.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "m";
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = "";
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ob_Puesto();
        String cli = (String )boxNombre.getSelectedItem();
        String id = "";
        if (estado.equals("n")) {
            btnCancelar.doClick();
            try {
                String querty = "select * from cliente where nombre ='" + cli +"'";
                rs=st.executeQuery(querty);
                    if(rs.next()){
                    id= rs.getString("idCliente");
                }
                
                
                String sql = "insert into auto (Placa, idCliente, Modelo, Marca, Tamaño, fecha_recibido ) "
                        + "values('" + txtPlaca.getText()  + "','"
                        + id + "','" + txtModelo.getText() + "','" + txtMarca.getText() + "','" + Puesto_t
                        + "','" + txtFecha.getText()+ "')";
                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Guardado ");
                MostrarTabla();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error, no se pudo guardar el registro" + ex.toString());
                System.out.println(ex);
            }
        }
        if (estado.equals("m")) {
            try {
                String querty = "select * from cliente where nombre ='" + cli +"'";
                rs=st.executeQuery(querty);
                    if(rs.next()){
                    id= rs.getString("idCliente");
                }
                    System.out.println("maikra"+id);
                //Toma el expediente del cuadro de texto txtExpediente y ese es el usuario que modifica
                String sql = "update auto set idCliente='" + id
                        + "', fecha_recibido='" + txtFecha.getText()
                        + "', Modelo='" + txtModelo.getText()
                        + "', Marca='" + txtMarca.getText()
                        + "', Tamaño='" + Puesto_t + "' where Placa='"+ txtPlaca.getText();

                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Modificado");
                MostrarTabla();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error y no se pudo modificar el registro" + ex.toString());
            }
            btnCancelar.doClick();
            boxNombre.setEnabled(false);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cli = (String )boxNombre.getSelectedItem();
        String id = "";
        try {
            String querty = "select * from cliente where nombre ='" + cli +"'";
                rs=st.executeQuery(querty);
                    if(rs.next()){
                    id= rs.getString("idCliente");
                }
            int op = JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar el usuario con el id de cliente " + id+ "?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                st.execute("delete from auto where idCliente='" + id + "'");
                btnCancelar.doClick();
                MostrarTabla();
                //if(rs.last()){
                    String sql = "select * from auto";
                    rs = st.executeQuery(sql);
                    if (rs.next()) {
                    txtPlaca.setText(rs.getString("Placa"));
                    txtModelo.setText(rs.getString("Modelo"));
                    txtMarca.setText(rs.getString("Marca"));
                    boxSizes.setSelectedIndex(Puesto_Index);
                    txtFecha.setText(rs.getString("fecha_recibido"));
                    } else {
                txtPlaca.setText("");
                txtModelo.setText("");
                txtMarca.setText("");
                txtFecha.setText("");
                    }

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.toString());
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String id = JOptionPane.showInputDialog("Escribe el número del servicio que deseas buscar");
        try {
            String sql = "select * from auto where idAuto=" + id;
            rs = st.executeQuery(sql);
            if (rs.next()) {

                    txtPlaca.setText(rs.getString("Placa"));
                    txtModelo.setText(rs.getString("Modelo"));
                    txtMarca.setText(rs.getString("Marca"));
                    boxSizes.setSelectedItem(rs.getString("Tamaño"));
                    txtFecha.setText(rs.getString("fecha_recibido"));
                    
              String querty = "select * from cliente where idcliente ='" + rs.getString("Idcliente") +"'";
              rs2=st2.executeQuery(querty);
              if(rs2.next()){
              boxNombre.setSelectedItem(rs2.getString("Nombre"));
              }
                    
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro el registro");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPlacaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlacaMousePressed
        if (txtPlaca.getText().equals("Ingrese la placa")) {
            txtPlaca.setText("");
            txtPlaca.setForeground(Color.black);
        }


        if (txtModelo.getText().trim().isEmpty()) {
            txtModelo.setText("Ingrese el modelo del carro");
            txtModelo.setForeground(Color.gray);
        }
        
        if (txtMarca.getText().trim().isEmpty()) {
            txtMarca.setText("Ingrese la marca del carro");
            txtMarca.setForeground(Color.gray);
        }

        if (txtFecha.getText().trim().isEmpty()) {
            txtFecha.setText("Ingrese la fecha");
            txtFecha.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtPlacaMousePressed

    private void tablaAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAutosMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tablaAutos.getModel();

        /*
            modelo.addColumn("idAuto"); 0
            modelo.addColumn("Placa"); 1
            modelo.addColumn("idCliente"); 2
            modelo.addColumn("Modelo"); 3
            modelo.addColumn("Marca"); 4
            modelo.addColumn("Tamaño"); 5
            modelo.addColumn("fecha_recibido"); 6
        */
        
        txtPlaca.setText(String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 1)));
        String idCli= (String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 2)));
                try{
            String sql = "select * from cliente where idCliente ='" + idCli +"'";
            rs=st.executeQuery(sql);
            if(rs.next()){
                boxNombre.setSelectedItem(rs.getString("Nombre"));
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
        txtModelo.setText(String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 3)));
        txtMarca.setText(String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 4)));
        switch (String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 5))) {
            case "Grande":
                boxSizes.setSelectedIndex(0);
                break;
            case "Mediano":
                boxSizes.setSelectedIndex(1);
                break;
            case "Pequeño":
                boxSizes.setSelectedIndex(2);
        }
        txtFecha.setText(String.valueOf(modelo.getValueAt(tablaAutos.getSelectedRow(), 6)));

    }//GEN-LAST:event_tablaAutosMouseClicked

    private void txtModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMousePressed
        if (txtModelo.getText().equals("Ingrese el modelo del carro")) {
            txtModelo.setText("");
            txtModelo.setForeground(Color.black);
        }

        if (txtPlaca.getText().trim().isEmpty()) {
            txtPlaca.setText("Ingrese la placa");
            txtPlaca.setForeground(Color.gray);
        }
        
        if (txtMarca.getText().trim().isEmpty()) {
            txtMarca.setText("Ingrese la marca del carro");
            txtMarca.setForeground(Color.gray);
        }

        if (txtFecha.getText().trim().isEmpty()) {
            txtFecha.setText("Ingrese la fecha");
            txtFecha.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtModeloMousePressed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        ob_Puesto();
        try {
            //seleccionamos antes del primero
            rs.beforeFirst();
            //ahora lo ponemos en el primero
            rs.next();
            //obtemos los datos que tiene

                    txtPlaca.setText(rs.getString("Placa"));
                    txtModelo.setText(rs.getString("Modelo"));
                    txtMarca.setText(rs.getString("Marca"));
                    boxSizes.setSelectedItem(rs.getString("Tamaño"));
                    txtFecha.setText(rs.getString("fecha_recibido"));
                    
                String querty = "select * from cliente where idcliente ='" + rs.getString("Idcliente") +"'";
                 rs2=st2.executeQuery(querty);
                if(rs2.next()){
                boxNombre.setSelectedItem(rs2.getString("Nombre"));
                }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            //verifico si no es esta en el primer registro en
            if (!rs.isFirst()) {
                //si lo no lo esta le resto uno y ahora va quedar en el antterior
                rs.absolute(rs.getRow() - 1);
                //si esta en el primer registro entonces lo mando al ultimo registro
            } else {
                //utilizo el metodo .last para que quede en el ultimo registro
                rs.last();
            }
            //traemos los datos que tiene los campos de entrada

                    txtPlaca.setText(rs.getString("Placa"));
                    txtModelo.setText(rs.getString("Modelo"));
                    txtMarca.setText(rs.getString("Marca"));
                    boxSizes.setSelectedIndex(Puesto_Index);
                    txtFecha.setText(rs.getString("fecha_recibido"));
                    
              String querty = "select * from cliente where idcliente ='" + rs.getString("Idcliente") +"'";
              rs2=st2.executeQuery(querty);
              if(rs2.next()){
              boxNombre.setSelectedItem(rs2.getString("Nombre"));
              }

        } catch (SQLException e) {
            //mandamos el mensaje del error
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void txtFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaMousePressed
        if (txtFecha.getText().equals("Ingrese la fecha")) {
            txtFecha.setText("");
            txtFecha.setForeground(Color.black);
        }
        
        if (txtPlaca.getText().trim().isEmpty()) {
            txtPlaca.setText("Ingrese la placa");
            txtPlaca.setForeground(Color.gray);
        }
        
        if (txtModelo.getText().trim().isEmpty()) {
            txtModelo.setText("Ingrese el modelo del carro");
            txtModelo.setForeground(Color.gray);
        }
        
        if (txtMarca.getText().trim().isEmpty()) {
            txtMarca.setText("Ingrese la marca del carro");
            txtMarca.setForeground(Color.gray);
        }
        

    }//GEN-LAST:event_txtFechaMousePressed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMarcaMousePressed
        if (txtMarca.getText().equals("Ingrese la marca del carro")) {
            txtMarca.setText("");
            txtMarca.setForeground(Color.black);
        }
        
        if (txtPlaca.getText().trim().isEmpty()) {
            txtPlaca.setText("Ingrese la placa");
            txtPlaca.setForeground(Color.gray);
        }
        
        if (txtModelo.getText().trim().isEmpty()) {
            txtModelo.setText("Ingrese el modelo del carro");
            txtModelo.setForeground(Color.gray);
        }
        
        if (txtFecha.getText().trim().isEmpty()) {
            txtFecha.setText("Ingrese la fecha");
            txtFecha.setForeground(Color.gray);
        } 
    

    
    }//GEN-LAST:event_txtMarcaMousePressed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void boxSizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSizesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxSizesActionPerformed

    private void txtModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyTyped
        //declaromos el caracter
        //tomamos el caracter 
        char lt = evt.getKeyChar();
        //verificamos que sea un numero de 0 y 9, para que nomas podemos datos enteros
        if((lt<'0' || lt>'9'))
        //filtra los caracteres 
        evt.consume();
    }//GEN-LAST:event_txtModeloKeyTyped

    private void txtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaFocusLost
         if (txtPlaca.getText().trim().equals("Ingrese la placa")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtPlaca.requestFocus();
            txtPlaca.setBackground(Color.red);
        } else {
            txtPlaca.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtPlacaFocusLost

    private void txtModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModeloFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloFocusLost

    private void txtMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMarcaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFocusLost

    private void txtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFocusLost

    private void boxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNombreActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNombre;
    private javax.swing.JComboBox<String> boxSizes;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAutos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
