
package proyecto;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class Cliente extends javax.swing.JInternalFrame {
    
    ResultSet rs;
    Statement st;
    String estado = "";
    
       private void conexion() {
        Connection cn;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tallerM", "root", "123a");
            //agrego los estos set para que pueda agregar selecionar los siguientes datos, y para pueda leer más consultas en la base de datos
            st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de Driver", "BD", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de SQL" + e.toString(), "BD", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        conexion();
        MostrarTabla();
        try {
            String sql = "select * from cliente";
            rs = st.executeQuery(sql);
            if (rs.next()) {
                
                txtNombreCli.setText(rs.getString("Nombre"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtMailCliente.setText(rs.getString("Correo_electronico"));
                txtTelefono.setText(rs.getString("Telefono"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla -Inicio-" + e.toString());
        }
    }
    
    private void MostrarTabla() {
        try {
            String sql = "Select idCliente, Nombre, Apellidos, Correo_electronico, Telefono from cliente";
            rs = st.executeQuery(sql);

            Object fila[] = new Object[5];
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("idCliente");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellidos");
            modelo.addColumn("Correo_electronico");
            modelo.addColumn("Telefono");

            if (!rs.isBeforeFirst()) {
                rs.beforeFirst();
            }
            while (rs.next()) {
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            tablaClientes.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla" + e.toString());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtNombreCli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMailCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cliente\n");
        setPreferredSize(new java.awt.Dimension(1376, 786));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtNombreCli.setText("Ingrese el nombre del cliente");
        txtNombreCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreCliFocusLost(evt);
            }
        });
        txtNombreCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreCliMousePressed(evt);
            }
        });
        txtNombreCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCliKeyTyped(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jLabel2.setText("Apellidos");

        txtApellidos.setText("Ingrese los apellidos del cliente");
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        txtApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidosMousePressed(evt);
            }
        });
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });

        jLabel3.setText("Correo electronico");

        txtMailCliente.setText("Ingrese el correo electronico del cliente");
        txtMailCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailClienteFocusLost(evt);
            }
        });
        txtMailCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMailClienteMousePressed(evt);
            }
        });

        jLabel4.setText("Telefono");

        txtTelefono.setText("Ingrese el telefeno del cliente");
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 396, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimero)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnUltimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnConsultar)
                    .addComponent(btnSalir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        
        try {
            //seleccionamos antes del primero
            rs.beforeFirst();
            //ahora lo ponemos en el primero
            rs.next();
            //obtemos los datos que tiene

            txtNombreCli.setText(rs.getString("Nombre"));
            txtApellidos.setText(rs.getString("Apellidos"));
            txtMailCliente.setText(rs.getString("Correo_electronico"));
            txtTelefono.setText(rs.getString("Telefono"));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            //verifico si no es esta en el primer registro en
            if (!rs.isFirst()) {
                //si lo no lo esta le resto uno y ahora va quedar en el antterior
                rs.absolute(rs.getRow() - 1);
                //si esta en el primer registro entonces lo mando al ultimo registro
            } else {
                //utilizo el metodo .last para que quede en el ultimo registro
                rs.last();
            }
            //traemos los datos que tiene los campos de entrada

                txtNombreCli.setText(rs.getString("Nombre"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtMailCliente.setText(rs.getString("Correo_electronico"));
                txtTelefono.setText(rs.getString("Telefono"));

        } catch (SQLException e) {
            //mandamos el mensaje del error
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            //utilizo el metodo para ponerlo en siguiente
            rs.next();

                txtNombreCli.setText(rs.getString("Nombre"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtMailCliente.setText(rs.getString("Correo_electronico"));
                txtTelefono.setText(rs.getString("Telefono"));

            if (rs.isLast()) //si esta en el ultimo registro  si esta en el ultimo, si esta
            //en el ultimo entonces lo que hago es mandalo al antepeultimo
            {
                rs.beforeFirst();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try {
            //metodo de ultimo registro para que lo ponga en lo
            rs.last();
            //poner todos los registro que tiene la tabla en los campos de entrada

                txtNombreCli.setText(rs.getString("Nombre"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtMailCliente.setText(rs.getString("Correo_electronico"));
                txtTelefono.setText(rs.getString("Telefono"));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "n";

        txtNombreCli.setText("");
        txtApellidos.setText("");
        txtMailCliente.setText("");
        txtTelefono.setText("");
      
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "m";
        System.out.println("hOL1");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = "";
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estado.equals("n")) {
            btnCancelar.doClick();
            try {

                String sql = "insert into cliente (Nombre, Apellidos, Correo_electronico, Telefono ) "
                + "values('" + txtNombreCli.getText() + "','" + txtApellidos.getText() + "','"
                + txtMailCliente.getText() + "','" + txtTelefono.getText() + "')";
                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Guardado ");
                MostrarTabla();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error, no se pudo guardar el registro" + ex.toString());
                System.out.println(ex);
            }
        }
        if (estado.equals("m")) {
            try {
                //Toma el expediente del cuadro de texto txtExpediente y ese es el usuario que modifica
                String sql = "update cliente set Nombre='" + txtNombreCli.getText()
                + "', Apellidos='" + txtApellidos.getText()
                + "', Correo_electronico='" + txtMailCliente.getText()+"' where Telefono="+txtTelefono.getText();
                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Modificado");
                MostrarTabla();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error y no se pudo modificar el registro" + ex.toString());
            }
            btnCancelar.doClick();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
        String sql= "Select idCliente from Empleado where Nombre= '"+ txtNombreCli.getText()+"'"+" and Apellidos='"+txtApellidos.getText()+"'";
        rs=st.executeQuery(sql);
        rs.next();
            System.out.println(rs.getString("idCliente"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.toString());
        }

        try {
            int op = JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar el cliente con el nombre " + txtNombreCli.getText() + "?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                st.execute("delete from cliente where idCliente ='"+ rs.getString("idCliente")  + "'");
                btnCancelar.doClick();
                MostrarTabla();
                //if(rs.last()){
                    String sql = "select * from cliente";
                    rs = st.executeQuery(sql);
                    if (rs.next()) {

                        txtNombreCli.setText(rs.getString("Nombre"));
                        txtApellidos.setText(rs.getString("Apellidos"));
                        txtMailCliente.setText(rs.getString("Correo_electronico"));
                        txtTelefono.setText(rs.getString("Telefono"));
                    } else {

                        txtNombreCli.setText("");
                        txtApellidos.setText("");
                        txtMailCliente.setText("");
                        txtTelefono.setText("");
                        txtTelefono.setText("");

                    }

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error " + ex.toString());
            }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreCliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCliMousePressed
        if (txtNombreCli.getText().equals("Ingrese el nombre del cliente")) {
            txtNombreCli.setText("");
            txtNombreCli.setForeground(Color.black);
        }
        if (txtApellidos.getText().trim().isEmpty()) {
            txtApellidos.setText("Ingrese los apellidos del cliente");
            txtApellidos.setForeground(Color.gray);
        }
        if (txtMailCliente.getText().trim().isEmpty()) {
            txtMailCliente.setText("Ingrese el correo electronico del cliente");
            txtMailCliente.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese el telefeno del cliente");
            txtTelefono.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtNombreCliMousePressed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();

        txtNombreCli.setText(String.valueOf(modelo.getValueAt(tablaClientes.getSelectedRow(), 1)));
        txtApellidos.setText(String.valueOf(modelo.getValueAt(tablaClientes.getSelectedRow(), 2)));
        txtMailCliente.setText(String.valueOf(modelo.getValueAt(tablaClientes.getSelectedRow(), 3)));
        txtTelefono.setText(String.valueOf(modelo.getValueAt(tablaClientes.getSelectedRow(), 4)));

    }//GEN-LAST:event_tablaClientesMouseClicked

    private void txtApellidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidosMousePressed
        if (txtApellidos.getText().equals("Ingrese los apellidos del cliente")) {
            txtApellidos.setText("");
            txtApellidos.setForeground(Color.black);
        }
        if (txtNombreCli.getText().trim().isEmpty()) {
            txtNombreCli.setText("Ingrese el nombre del cliente");
            txtNombreCli.setForeground(Color.gray);
        }
        if (txtMailCliente.getText().trim().isEmpty()) {
            txtMailCliente.setText("Ingrese el correo electronico del cliente");
            txtMailCliente.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese el telefeno del cliente");
            txtTelefono.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtApellidosMousePressed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtMailClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMailClienteMousePressed
        if (txtMailCliente.getText().equals("Ingrese el correo electronico del cliente")) {
            txtMailCliente.setText("");
            txtMailCliente.setForeground(Color.black);
        }
        if (txtNombreCli.getText().trim().isEmpty()) {
            txtNombreCli.setText("Ingrese el nombre del cliente");
            txtNombreCli.setForeground(Color.gray);
        }
        if (txtApellidos.getText().trim().isEmpty()) {
            txtApellidos.setText("Ingrese los apellidos del cliente");
            txtApellidos.setForeground(Color.gray);
        }
        
        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese el telefeno del cliente");
            txtTelefono.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtMailClienteMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtTelefono.getText().equals("Ingrese el telefeno del cliente")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }

        if (txtNombreCli.getText().trim().isEmpty()) {
            txtNombreCli.setText("Ingrese el nombre del cliente");
            txtNombreCli.setForeground(Color.gray);
        }

        if (txtApellidos.getText().trim().isEmpty()) {
            txtApellidos.setText("Ingrese los apellidos del cliente");
            txtApellidos.setForeground(Color.gray);
        }
        if (txtMailCliente.getText().trim().isEmpty()) {
            txtMailCliente.setText("Ingrese el correo electronico del cliente");
            txtMailCliente.setForeground(Color.gray);
        }

 
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        //declaromos el caracter
        //tomamos el caracter 
        char lt = evt.getKeyChar();
        //verificamos que sea un numero de 0 y 9, para que nomas podemos datos enteros
        if((lt<'0' || lt>'9'))
        //filtra los caracteres 
        evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreCliFocusLost
         if (txtNombreCli.getText().trim().equals("Ingrese el nombre del cliente")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtNombreCli.requestFocus();
            txtNombreCli.setBackground(Color.red);
        } else {
            txtNombreCli.setBackground(Color.white);
        }
     }//GEN-LAST:event_txtNombreCliFocusLost

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
         if (txtApellidos.getText().trim().equals("Ingrese los apellidos del cliente")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtApellidos.requestFocus();
            txtApellidos.setBackground(Color.red);
        } else {
            txtApellidos.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtMailClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailClienteFocusLost
         if (txtMailCliente.getText().trim().equals("Ingrese el correo electronico del cliente")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtMailCliente.requestFocus();
            txtMailCliente.setBackground(Color.red);
        } else {
            txtMailCliente.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtMailClienteFocusLost

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
         if (txtTelefono.getText().trim().equals("Ingrese el correo electronico del cliente")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtTelefono.requestFocus();
            txtTelefono.setBackground(Color.red);
        } else {
            txtTelefono.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtNombreCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCliKeyTyped
          int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    } 
    }//GEN-LAST:event_txtNombreCliKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
   int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    } 
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String id = JOptionPane.showInputDialog("Escribe el id del cliente");
        try {
            String sql = "select * from Cliente where idCliente=" + id;
            rs = st.executeQuery(sql);
            if (rs.next()) {

                txtNombreCli.setText(rs.getString("Nombre"));
                txtApellidos.setText(rs.getString("Apellidos"));
                txtMailCliente.setText(rs.getString("Correo_electronico"));
                txtTelefono.setText(rs.getString("Telefono"));
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro el registro");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtMailCliente;
    private javax.swing.JTextField txtNombreCli;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
