package proyecto;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angel
 */
public class empleado_Reg extends javax.swing.JInternalFrame {

    ResultSet rs;
    Statement st;
    String estado = "";

    private void conexion() {
        Connection cn;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tallerM", "root", "123a");
            //agrego los estos set para que pueda agregar selecionar los siguientes datos, y para pueda leer más consultas en la base de datos
            st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error de Driver", "BD", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de SQL" + e.toString(), "BD", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form empleado_Reg
     */
    public empleado_Reg() {
        initComponents();
        conexion();
        MostrarTabla();
        try {
            String sql = "select * from empleado";
            rs = st.executeQuery(sql);
            if (rs.next()) {

                txtNombre.setText(rs.getString("Nombre"));
                txtApe_P.setText(rs.getString("Apellido_Paterno"));
                txtApe_M.setText(rs.getString("Apellido_Materno"));
                txtEdad.setText(rs.getString("Edad"));
                boxPuestos.setSelectedIndex(Puesto_Index);
                txtTelefono.setText(rs.getString("telefono"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla -Inicio-" + e.toString());
        }

    }

    String Puesto_t = "";
    int Puesto_Index = 0;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApe_P = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApe_M = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPrimero = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        boxPuestos = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Empleados");

        jLabel1.setText("Nombre");

        txtNombre.setText("Ingrese su nombre");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("Apellido_Paterno");

        txtApe_P.setText("Ingrese su apellido");
        txtApe_P.setCaretColor(new java.awt.Color(0, 0, 0));
        txtApe_P.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApe_PFocusLost(evt);
            }
        });
        txtApe_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApe_PMousePressed(evt);
            }
        });
        txtApe_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApe_PActionPerformed(evt);
            }
        });
        txtApe_P.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApe_PKeyTyped(evt);
            }
        });

        jLabel3.setText("Apellido Materno");

        txtApe_M.setText("Ingrese su apellido");
        txtApe_M.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApe_MFocusLost(evt);
            }
        });
        txtApe_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApe_MMousePressed(evt);
            }
        });
        txtApe_M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApe_MKeyTyped(evt);
            }
        });

        jLabel4.setText("Edad");

        jLabel5.setText("Cargo");

        txtEdad.setText("Ingrese su edad");
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });
        txtEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEdadMousePressed(evt);
            }
        });
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        jLabel6.setText("Telefono");

        txtTelefono.setText("Ingrese su telefono");
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        boxPuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Mecanico", "Gerente", "Limpieza" }));
        boxPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPuestosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addComponent(txtApe_P, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addComponent(txtApe_M, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(916, 916, 916))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar)
                            .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)
                        .addGap(223, 223, 223))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtApe_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrimero)
                            .addComponent(btnAnterior)
                            .addComponent(btnSiguiente)
                            .addComponent(btnUltimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNuevo)
                                .addComponent(btnModificar)
                                .addComponent(btnCancelar)
                                .addComponent(btnGuardar)
                                .addComponent(btnEliminar)
                                .addComponent(btnSalir)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtApe_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void MostrarTabla() {
        try {
            String sql = "Select * from empleado";
            rs = st.executeQuery(sql);

            Object fila[] = new Object[7];
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("idEmpleado");//1
            modelo.addColumn("Nombre");//2
            modelo.addColumn("Apellido_Paterno");//3
            modelo.addColumn("Apellido_Materno");//4
            modelo.addColumn("Edad");//5
            modelo.addColumn("Cargo");//6
            modelo.addColumn("Telefono");//7

            if (!rs.isBeforeFirst()) {
                rs.beforeFirst();
            }
            while (rs.next()) {
                for (int i = 0; i < 7; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            tablaEmpleados.setModel(modelo);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se pudo mostrar la tabla" + e.toString());
        }
    }

    private void ob_Puesto() {
        int Puesto = this.boxPuestos.getSelectedIndex();
        switch (Puesto) {
            case 0:
                Puesto_t = "Administrativo";
                Puesto_Index = 0;
                break;
            case 1:
                Puesto_t = "Mecanico";
                Puesto_Index = 1;
            case 2:
                Puesto_t = "Gerente";
                Puesto_Index = 2;
                break;
            case 3:
                Puesto_t = "Limpieza";
                Puesto_Index = 3;

        }
    }


    private void txtApe_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe_PActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed
        ob_Puesto();
        try {
            //seleccionamos antes del primero
            rs.beforeFirst();
            //ahora lo ponemos en el primero
            rs.next();
            //obtemos los datos que tiene

            txtNombre.setText(rs.getString("Nombre"));
            txtApe_P.setText(rs.getString("Apellido_Paterno"));
            txtApe_M.setText(rs.getString("Apellido_Materno"));
            txtEdad.setText(rs.getString("Edad"));
            boxPuestos.setSelectedItem(rs.getString("Cargo"));
            txtTelefono.setText(rs.getString("telefono"));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try {
            //verifico si no es esta en el primer registro en
            if (!rs.isFirst()) {
                //si lo no lo esta le resto uno y ahora va quedar en el antterior
                rs.absolute(rs.getRow() - 1);
                //si esta en el primer registro entonces lo mando al ultimo registro
            } else {
                //utilizo el metodo .last para que quede en el ultimo registro
                rs.last();
            }
            //traemos los datos que tiene los campos de entrada

            txtNombre.setText(rs.getString("Nombre"));
            txtApe_P.setText(rs.getString("Apellido_Paterno"));
            txtApe_M.setText(rs.getString("Apellido_Materno"));
            txtEdad.setText(rs.getString("Edad"));
            boxPuestos.setSelectedItem(rs.getString("Cargo"));
            txtTelefono.setText(rs.getString("Telefono"));

        } catch (SQLException e) {
            //mandamos el mensaje del error
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            //utilizo el metodo para ponerlo en siguiente
            rs.next();

            txtNombre.setText(rs.getString("Nombre"));
            txtApe_P.setText(rs.getString("Apellido_Paterno"));
            txtApe_M.setText(rs.getString("Apellido_Materno"));
            txtEdad.setText(rs.getString("Edad"));
            boxPuestos.setSelectedItem(rs.getString("Cargo"));
            txtTelefono.setText(rs.getString("Telefono"));

            if (rs.isLast()) //si esta en el ultimo registro  si esta en el ultimo, si esta
            //en el ultimo entonces lo que hago es mandalo al antepeultimo
            {
                rs.beforeFirst();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try {
            //metodo de ultimo registro para que lo ponga en lo
            rs.last();
            //poner todos los registro que tiene la tabla en los campos de entrada

            txtNombre.setText(rs.getString("Nombre"));
            txtApe_P.setText(rs.getString("Apellido_Paterno"));
            txtApe_M.setText(rs.getString("Apellido_Materno"));
            txtEdad.setText(rs.getString("Edad"));
            boxPuestos.setSelectedItem(rs.getString("Cargo"));
            txtTelefono.setText(rs.getString("Telefono"));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error " + e.toString());
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "n";

        txtNombre.setText("");
        txtApe_P.setText("");
        txtApe_M.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnCancelar.setEnabled(true);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnConsultar.setEnabled(false);
        estado = "m";
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        estado = "";
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnConsultar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ob_Puesto();
        if (estado.equals("n")) {
            btnCancelar.doClick();
            try {

                String sql = "insert into empleado (Nombre, Apellido_Paterno, Apellido_Materno, Edad, Cargo, Telefono) "
                        + "values('" + txtNombre.getText() + "','" + txtApe_P.getText() + "','"
                        + txtApe_M.getText() + "','" + txtEdad.getText() + "','" + Puesto_t + "','" + txtTelefono.getText()
                        + "')";
                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Guardado ");
                MostrarTabla();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error, no se pudo guardar el registro" + ex.toString());
                System.out.println(ex);
            }
        }
        if (estado.equals("m")) {
            try {
                //Toma el expediente del cuadro de texto txtExpediente y ese es el usuario que modifica
                String sql = "update empleado set Nombre='" + txtNombre.getText()
                        + "', Apellido_Paterno='" + txtApe_P.getText()
                        + "', Apellido_Materno='" + txtApe_M.getText()
                        + "', Edad='" + txtEdad.getText()
                        + "', Cargo='" + Puesto_t +"' where Telefono="+txtTelefono.getText();

                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Registro Modificado");
                MostrarTabla();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Ocurrio un error y no se pudo modificar el registro" + ex.toString());
            }
            btnCancelar.doClick();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            String sql = "Select IdEmpleado from Empleado where Nombre= '" + txtNombre.getText() + "'" + " and Apellido_Materno='" + txtApe_M.getText() + "'";
            rs = st.executeQuery(sql);
            rs.next();

            System.out.println(rs.getString("idEmpleado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.toString());
        }

        try {
            int op = JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar el empleado con el nombre " + txtNombre.getText() + "?", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                st.execute("delete from empleado where IdEmpleado ='" + rs.getString("idEmpleado") + "'");
                btnCancelar.doClick();
                MostrarTabla();
                //if(rs.last()){
                String sql = "select * from empleado";
                rs = st.executeQuery(sql);
                if (rs.next()) {

                    txtNombre.setText(rs.getString("Nombre"));
                    txtApe_P.setText(rs.getString("Apellido_Paterno"));
                    txtApe_M.setText(rs.getString("Apellido_Materno"));
                    txtEdad.setText(rs.getString("Edad"));
                    boxPuestos.setSelectedIndex(Puesto_Index);
                    txtTelefono.setText(rs.getString("telefono"));
                } else {

                    txtNombre.setText("");
                    txtApe_P.setText("");
                    txtApe_M.setText("");
                    txtEdad.setText("");
                    txtTelefono.setText("");

                }

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        if (txtNombre.getText().equals("Ingrese su nombre")) {
            txtNombre.setText("");
            txtNombre.setForeground(Color.black);
        }
        if (txtApe_P.getText().trim().isEmpty()) {
            txtApe_P.setText("Ingrese su apellido");
            txtApe_P.setForeground(Color.gray);
        }
        if (txtApe_M.getText().trim().isEmpty()) {
            txtApe_M.setText("Ingrese su apellido");
            txtApe_M.setForeground(Color.gray);
        }

        if (txtEdad.getText().trim().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese su telefono");
            txtTelefono.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtNombreMousePressed

    private void txtApe_PMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApe_PMousePressed
        if (txtApe_P.getText().equals("Ingrese su apellido")) {
            txtApe_P.setText("");
            txtApe_P.setForeground(Color.black);
        }
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApe_M.getText().trim().isEmpty()) {
            txtApe_M.setText("Ingrese su apellido");
            txtApe_M.setForeground(Color.gray);
        }

        if (txtEdad.getText().trim().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese su telefono");
            txtTelefono.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtApe_PMousePressed

    private void boxPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPuestosActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleados.getModel();

        txtNombre.setText(String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 1)));
        txtApe_P.setText(String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 2)));
        txtApe_M.setText(String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 3)));
        txtEdad.setText(String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 4)));
        switch (String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 5))) {
            case "Administrativo":
                boxPuestos.setSelectedIndex(0);
                break;
            case "Mecanico":
                boxPuestos.setSelectedIndex(1);
                break;
            case "Gerente":
                boxPuestos.setSelectedIndex(2);
        }
        txtTelefono.setText(String.valueOf(modelo.getValueAt(tablaEmpleados.getSelectedRow(), 6)));


    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void txtApe_MMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApe_MMousePressed
        if (txtApe_M.getText().equals("Ingrese su apellido")) {
            txtApe_M.setText("");
            txtApe_M.setForeground(Color.black);
        }
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.gray);
        }
        if (txtApe_P.getText().trim().isEmpty()) {
            txtApe_P.setText("Ingrese su apellido");
            txtApe_P.setForeground(Color.gray);
        }

        if (txtEdad.getText().trim().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese su telefono");
            txtTelefono.setForeground(Color.gray);
        }


    }//GEN-LAST:event_txtApe_MMousePressed

    private void txtEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEdadMousePressed
        if (txtEdad.getText().equals("Ingrese su edad")) {
            txtEdad.setText("");
            txtEdad.setForeground(Color.black);
        }

        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.gray);
        }

        if (txtApe_P.getText().trim().isEmpty()) {
            txtApe_P.setText("Ingrese su apellido");
            txtApe_P.setForeground(Color.gray);
        }
        if (txtApe_M.getText().trim().isEmpty()) {
            txtApe_M.setText("Ingrese su apellido");
            txtApe_M.setForeground(Color.gray);
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("Ingrese su telefono");
            txtTelefono.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtEdadMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if (txtTelefono.getText().equals("Ingrese su telefono")) {
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.black);
        }

        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("Ingrese su nombre");
            txtNombre.setForeground(Color.gray);
        }

        if (txtApe_P.getText().trim().isEmpty()) {
            txtApe_P.setText("Ingrese su apellido");
            txtApe_P.setForeground(Color.gray);
        }
        if (txtApe_M.getText().trim().isEmpty()) {
            txtApe_M.setText("Ingrese su apellido");
            txtApe_M.setForeground(Color.gray);
        }
        if (txtEdad.getText().trim().isEmpty()) {
            txtEdad.setText("Ingrese su edad");
            txtEdad.setForeground(Color.gray);
        }

    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if (txtNombre.getText().trim().equals("Ingrese su nombre")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtNombre.requestFocus();
            txtNombre.setBackground(Color.red);
        } else {
            txtNombre.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtApe_PFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApe_PFocusLost
        if (txtApe_P.getText().trim().equals("Ingrese su apellido")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtApe_P.requestFocus();
            txtApe_P.setBackground(Color.red);
        } else {
            txtApe_P.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtApe_PFocusLost

    private void txtApe_MFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApe_MFocusLost
         if (txtApe_M.getText().trim().equals("Ingrese su apellido")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtApe_M.requestFocus();
            txtApe_M.setBackground(Color.red);
        } else {
            txtApe_M.setBackground(Color.white);
        }           
    }//GEN-LAST:event_txtApe_MFocusLost

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
         if (txtEdad.getText().trim().equals("Ingrese su edad")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtEdad.requestFocus();
            txtEdad.setBackground(Color.red);
        } else {
            txtEdad.setBackground(Color.white);
        }
     }//GEN-LAST:event_txtEdadFocusLost

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
         if (txtEdad.getText().trim().equals("Ingrese su telefono")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtEdad.requestFocus();
            txtEdad.setBackground(Color.red);
        } else {
            txtEdad.setBackground(Color.white);
        }   
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        //declaromos el caracter
        //tomamos el caracter 
        char lt = evt.getKeyChar();
        //verificamos que sea un numero de 0 y 9, para que nomas podemos datos enteros
        if((lt<'0' || lt>'9'))
        //filtra los caracteres 
        evt.consume();
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
   int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }    
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
       //declaromos el caracter
        //tomamos el caracter 
        char lt = evt.getKeyChar();
        //verificamos que sea un numero de 0 y 9, para que nomas podemos datos enteros
        if((lt<'0' || lt>'9'))
        //filtra los caracteres 
        evt.consume();
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtApe_PKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApe_PKeyTyped
           int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    } 
    }//GEN-LAST:event_txtApe_PKeyTyped

    private void txtApe_MKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApe_MKeyTyped
           int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    } 
     
    }//GEN-LAST:event_txtApe_MKeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String id = JOptionPane.showInputDialog("Escribe el id del Empleado");
        try {
            String sql = "select * from Empleado where IdEmpleado=" + id;
            rs = st.executeQuery(sql);
            if (rs.next()) {

                txtNombre.setText(rs.getString("Nombre"));
                txtApe_P.setText(rs.getString("Apellido_Paterno"));
                txtApe_M.setText(rs.getString("Apellido_Materno"));
                txtEdad.setText(rs.getString("Edad"));
                boxPuestos.setSelectedItem(rs.getString("Cargo"));
                txtTelefono.setText(rs.getString("telefono"));
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro el registro");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPuestos;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtApe_M;
    private javax.swing.JTextField txtApe_P;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
