package proyecto;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Login extends javax.swing.JFrame {
    // creo variables para la poder mover la pantalla 
    //estas son de tipo entero para saber donde se encuentra la panatalla
    int xMouse, yMouse;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //selecciono la imagen que voy a utilizar
        ImageIcon image = new ImageIcon("src/Imagenes/logo.png");
        //cambio las disemsiones de la imagen para que se muestre como esta en el panel
        Icon icon = new ImageIcon (image.getImage().getScaledInstance(this.Logo_empresa.getWidth(),this.Logo_empresa.getHeight(), Image.SCALE_DEFAULT));
        this.Logo_empresa.setIcon(icon);
        this.repaint();
        
        ImageIcon image2 = new ImageIcon("src/Imagenes/favoriteIcon1.png");
        Icon icon2 = new ImageIcon (image2.getImage().getScaledInstance(this.Logo_po.getWidth(),this.Logo_po.getHeight(), Image.SCALE_DEFAULT));
        this.Logo_po.setIcon(icon2);
        this.repaint();
        
       
    }
    
    ResultSet rs; //traer el resulltado con que es como un select
    Statement st; //ejecutar las consultas de sql
 
//Método para conectarse a la base de datos
private void conexion(){
        Connection cn;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/tallerM","root","123a");
            st=cn.createStatement();
        }catch(ClassNotFoundException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error de Driver","BD",JOptionPane.ERROR_MESSAGE);
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Error de SQL" +e.toString(),"BD",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo_empresa = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Logo_po = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        contraseñalabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        usuariolabel = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pInicio = new javax.swing.JPanel();
        jLInicio = new javax.swing.JLabel();
        pMoviendo_screen = new javax.swing.JPanel();
        pCerrar = new javax.swing.JPanel();
        jL_Cerrar = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesion");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Logo_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 210, 190));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 400, 460));
        jPanel1.add(Logo_po, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 270, 140));

        Inicio.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        Inicio.setForeground(new java.awt.Color(0, 204, 255));
        Inicio.setText("Inicio de Sesion");
        jPanel1.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 50));

        contraseñalabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        contraseñalabel.setForeground(new java.awt.Color(0, 204, 255));
        contraseñalabel.setText("Contraseña:");
        jPanel1.add(contraseñalabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 290, -1));

        usuariolabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        usuariolabel.setForeground(new java.awt.Color(0, 204, 255));
        usuariolabel.setText("Usuario:");
        jPanel1.add(usuariolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("  Ingrese su nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCaretColor(new java.awt.Color(0, 0, 0));
        txtUsuario.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 30));

        pInicio.setBackground(new java.awt.Color(0, 176, 218));

        jLInicio.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInicio.setText("Inicio");
        jLInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLInicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pInicioLayout = new javax.swing.GroupLayout(pInicio);
        pInicio.setLayout(pInicioLayout);
        pInicioLayout.setHorizontalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pInicioLayout.setVerticalGroup(
            pInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        pMoviendo_screen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pMoviendo_screenMouseDragged(evt);
            }
        });
        pMoviendo_screen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pMoviendo_screenMousePressed(evt);
            }
        });

        jL_Cerrar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jL_Cerrar.setForeground(new java.awt.Color(0, 0, 0));
        jL_Cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Cerrar.setText("X");
        jL_Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jL_Cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jL_Cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_CerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jL_CerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jL_CerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pCerrarLayout = new javax.swing.GroupLayout(pCerrar);
        pCerrar.setLayout(pCerrarLayout);
        pCerrarLayout.setHorizontalGroup(
            pCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pCerrarLayout.setVerticalGroup(
            pCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCerrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jL_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jL_Cerrar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout pMoviendo_screenLayout = new javax.swing.GroupLayout(pMoviendo_screen);
        pMoviendo_screen.setLayout(pMoviendo_screenLayout);
        pMoviendo_screenLayout.setHorizontalGroup(
            pMoviendo_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMoviendo_screenLayout.createSequentialGroup()
                .addComponent(pCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 670, Short.MAX_VALUE))
        );
        pMoviendo_screenLayout.setVerticalGroup(
            pMoviendo_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMoviendo_screenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pMoviendo_screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        pass.setForeground(new java.awt.Color(204, 204, 204));
        pass.setText("*********");
        pass.setBorder(null);
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 290, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pMoviendo_screenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMoviendo_screenMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_pMoviendo_screenMousePressed

    private void pMoviendo_screenMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMoviendo_screenMouseDragged
        //creo variables para saber donde esta el mouse en toda la pantalla 
        //ya no solo en donde esta en el programa para que lo podamos arrastrar
        //correctamente
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //establece la localizacion de la ventana en donde queramos
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_pMoviendo_screenMouseDragged

    private void jL_CerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jL_CerrarMouseClicked

    private void jL_CerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CerrarMouseEntered
        //darle color cuando entra al label
        pCerrar.setBackground(Color.red);
        //cambia de color el texto que tiene el jPanel
       jL_Cerrar.setForeground(new Color(221,221,221));
    }//GEN-LAST:event_jL_CerrarMouseEntered

    private void jL_CerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_CerrarMouseExited
        //darle color cuando entra al label
        pCerrar.setBackground(new Color(221,221,221));
        //cambia de color el texto que tiene el jPanel
        jL_Cerrar.setForeground(Color.black);
    }//GEN-LAST:event_jL_CerrarMouseExited

    private void jLInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseEntered
        pInicio.setBackground(new Color(0,113,140));
    }//GEN-LAST:event_jLInicioMouseEntered

    private void jLInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseExited
        pInicio.setBackground(new Color(0,176,218));
    }//GEN-LAST:event_jLInicioMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("  Ingrese su nombre de usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);
        }
      if(String.valueOf(pass.getPassword()).trim().isEmpty()){
          pass.setText("*********");
          pass.setForeground(Color.gray);
      }
    }//GEN-LAST:event_txtUsuarioMousePressed
    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed

    }//GEN-LAST:event_passActionPerformed

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed

        if(String.valueOf(pass.getPassword()).equals("*********")){
         pass.setText("");
         pass.setForeground(Color.black);
        }
        
        if(txtUsuario.getText().trim().isEmpty()){
            txtUsuario.setText("  Ingrese su nombre de usuario");
            txtUsuario.setForeground(Color.gray);
         
            
        }
    }//GEN-LAST:event_passMousePressed

    private void jLInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseClicked
                try{
           String usr = txtUsuario.getText();
           char p[]=pass.getPassword();
            String pass1= new String(p);
            conexion();
            String sql="SELECT * FROM Usuarios WHERE Usuario='"+usr+"' and Contraseña='"+pass1+"'";
            rs=st.executeQuery(sql);
            if(rs.next()){
                Principal Regristro = new Principal();
                Regristro.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrectos");
            }
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Error de SQL" +e.toString(),"BD",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLInicioMouseClicked

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().trim().equals("Ingrese su nombre")) {
            JOptionPane.showMessageDialog(this, "No dejes el campo vacio");
            txtUsuario.requestFocus();
            txtUsuario.setBackground(Color.red);
        } else {
            txtUsuario.setBackground(Color.white);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Logo_empresa;
    private javax.swing.JLabel Logo_po;
    private javax.swing.JLabel contraseñalabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jL_Cerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pCerrar;
    private javax.swing.JPanel pInicio;
    private javax.swing.JPanel pMoviendo_screen;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usuariolabel;
    // End of variables declaration//GEN-END:variables
}
