package proyecto;

/**
 *
 * @author Angel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCerrar = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenuItem();
        jmUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenuServicio = new javax.swing.JMenuItem();
        jmenuAuto = new javax.swing.JMenuItem();
        jmSueldos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmEmp = new javax.swing.JMenuItem();
        jmenuCliente = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1388, Short.MAX_VALUE)
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jmCerrar.setText("Cerrar");
        jmCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(jmCerrar);

        jmSalir.setText("Salir");
        jMenu1.add(jmSalir);

        jmUsuario.setText("Usuario");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Servicio");

        jmenuServicio.setText("Servicio");
        jmenuServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuServicioActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuServicio);

        jmenuAuto.setText("Auto");
        jmenuAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAutoActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuAuto);

        jmSueldos.setText("Sueldos");
        jmSueldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSueldosActionPerformed(evt);
            }
        });
        jMenu2.add(jmSueldos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empleado");

        jmEmp.setText("Emp");
        jmEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEmpActionPerformed(evt);
            }
        });
        jMenu3.add(jmEmp);

        jmenuCliente.setText("Cliente");
        jmenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuCliente);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEmpActionPerformed
        empleado_Reg emp = new empleado_Reg();
        jpPrincipal.add(emp);
        emp.setVisible(true);    }//GEN-LAST:event_jmEmpActionPerformed

    private void jmenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuClienteActionPerformed
        Cliente cli = new Cliente();
        jpPrincipal.add(cli);
        cli.setVisible(true);
    }//GEN-LAST:event_jmenuClienteActionPerformed

    private void jmenuServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuServicioActionPerformed
        Servicio ser = new Servicio();
        jpPrincipal.add(ser);
        ser.setVisible(true);
    }//GEN-LAST:event_jmenuServicioActionPerformed

    private void jmenuAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAutoActionPerformed
        Auto au = new Auto();
        jpPrincipal.add(au);
        au.setVisible(true);
    }//GEN-LAST:event_jmenuAutoActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        Usuarios user = new Usuarios();
        jpPrincipal.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jmCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCerrarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmCerrarActionPerformed

    private void jmSueldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSueldosActionPerformed
        Sueldos su = new Sueldos();
        jpPrincipal.add(su);
        su.setVisible(true);
    }//GEN-LAST:event_jmSueldosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem jmCerrar;
    private javax.swing.JMenuItem jmEmp;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmSueldos;
    private javax.swing.JMenuItem jmUsuario;
    private javax.swing.JMenuItem jmenuAuto;
    private javax.swing.JMenuItem jmenuCliente;
    private javax.swing.JMenuItem jmenuServicio;
    private javax.swing.JDesktopPane jpPrincipal;
    // End of variables declaration//GEN-END:variables
}
